### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by successed** [prettydude/F3Name#10]
`[02:36:31] [Netty Worker IO Thread #4/WARN]: Error dispatching event ServerConnectedEvent(player=Seppers, server=net.md_5.bungee.ServerConnection@3f3e481b) to listener ua.coolboy.f3name.bungee.BungeeEventListener@1ec7d8b3
java.lang.IllegalArgumentException: Can't find player with UUID 9fae37ca-ed75-3b3c-9ff9-62685a369977
	at ua.coolboy.f3name.bungee.F3NameBungee.send(F3NameBungee.java:312) ~[?:?]
	at ua.coolboy.f3name.bungee.BungeeEventListener.onJoin(BungeeEventListener.java:30) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:433) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:212) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

**Comment by zubiden** [comment]
Can you reproduce that exception with [this](https://www.dropbox.com/s/hmb4s6ilkkk88b2/F3Name.jar) version?
