### ISSUE TITLE
Error with PlaceholderAPI-2.10.9

### ISSUE THREAD

**Issue by SrBedrock** [prettydude/F3Name#13]
```
[08:45:37 ERROR]: Could not pass event PlayerJoinEvent to F3Name v3.2.0
java.lang.NoSuchMethodError: 'java.lang.String me.clip.placeholderapi.PlaceholderAPIPlugin.getUptime()'
at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:130) ~[?:?]
at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
at ua.coolboy.f3name.bukkit.hooks.PAPIHook.getPAPIString(PAPIHook.java:16) ~[?:?]
at ua.coolboy.f3name.bukkit.F3NameBukkit.send(F3NameBukkit.java:358) ~[?:?]
at ua.coolboy.f3name.bukkit.F3NameBukkit.send(F3NameBukkit.java:372) ~[?:?]
at ua.coolboy.f3name.bukkit.F3NameBukkit.onJoin(F3NameBukkit.java:166) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor36.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:240) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$1(PlayerList.java:187) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:422) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1239) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at java.lang.Thread.run(Thread.java:832) [?:?]
[08:45:37 INFO]: ThiagoROX[/177.91.72.67:59512] logged in with entity id 1 at ([lobby]0.49028176640877724, 63.0, 0.25577898101938357)
[08:45:37 INFO]: [FastLogin] Player info LOGIN command for ThiagoROX from proxy
[08:45:37 INFO]: [FastLogin] Delaying force login until join event fired?: false
[08:45:37 INFO]: [FastLogin] Logging player ThiagoROX in
[08:45:39 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[08:45:50 WARN]: [F3Name] Plugin F3Name v3.2.0 generated an exception while executing task 168
java.lang.NoSuchMethodError: 'java.lang.String me.clip.placeholderapi.PlaceholderAPIPlugin.getUptime()'
at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:130) ~[?:?]
at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
at ua.coolboy.f3name.bukkit.hooks.PAPIHook.getPAPIString(PAPIHook.java:16) ~[?:?]
at ua.coolboy.f3name.bukkit.F3NameBukkit.send(F3NameBukkit.java:358) ~[?:?]
at ua.coolboy.f3name.bukkit.BukkitF3Runnable.run(BukkitF3Runnable.java:85) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Tuinity-"3cdf7e4"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by zubiden** [comment]
Update ServerExpansion
Related commit: https://github.com/PlaceholderAPI/Server-Expansion/commit/bf608623a29f2806c8fda491969664de0ab4ceff
