### ISSUE TITLE
Failed to get resource info from spiget.org

### ISSUE THREAD

**Issue by mrfloris** [prettydude/F3Name#14]
Today I started the server and I noticed the following java.io.IOException from F3Name in the console. 
Manually loading `http://api.spiget.org/v2/resources/58997?ut=1614242223073` in the browser works for me though.
```
[09:38:03 WARN]: [F3Name] Failed to get resource info from spiget.org
java.io.IOException: Server returned HTTP response code: 504 for URL: http://api.spiget.org/v2/resources/58997?ut=1614242223073
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at ua.coolboy.f3name.spiget.updater.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-497]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-497]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
>
```
```
> ver F3Name
[09:40:37 INFO]: F3Name version 3.2.0
[09:40:37 INFO]: Author: Cool_boy
> ver
[09:40:37 INFO]: This server is running Paper version git-Paper-497 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[09:40:37 INFO]: Checking version, please wait...
[09:40:38 INFO]: Previous version: git-Paper-496 (MC: 1.16.5)
[09:40:38 INFO]: You are running the latest version
>
```

**Comment by zubiden** [comment]
Seems like temporary downtime on spiget side. If the error continues to appear, you can turn off auto-update in config

**Comment by mrfloris** [comment]
Okay, thank you for the follow up and I will keep an eye on it. Question though, what do I add to `config.yml` to disable the update check?
```yaml
#  ______ ____  _   _                       #
# |  ____|___ \| \ | |                      #
# | |__    __) |  \| | __ _ _ __ ___   ___  #
# |  __|  |__ <| . ` |/ _` | '_ ` _ \ / _ \ #
# | |     ___) | |\  | (_| | | | | | |  __/ #
# |_|    |____/|_| \_|\__,_|_| |_| |_|\___| #
#                                           #

groups:
  #Default group. DO NOT REMOVE!
  everyone:
    f3names:
      - '&6&l1MoreBlock.com&r&6 version 2.8.7&r'
      - '&e&l1MoreBlock.com&r&6 version 2.8.7&r'
      - '&c&l1MoreBlock.com&r&6 version 2.8.7&r'
      - '&9&l1MoreBlock.com&r&6 version 2.8.7&r'
      - '&b&l1MoreBlock.com&r&6 version 2.8.7&r'
      - '&3&l1MoreBlock.com&r&6 version 2.8.7&r'
    #Shuffle that list before displaying?
    shuffle: false
    #Refresh rate in ticks (1 second = 20 ticks)
    update-time: 240
  #Some example. You can edit or remove this
    #Shuffle and update-time are optional, their default values shown above

#If set to true, disables this plugin and gives bungeecord side plugin ability to send
#messages through this plugin. It allows bungee to use hooked plugins (PlaceholderAPI, Vault, LuckPerms)
bungeecord-as-primary: false

#Use colored console. Disable this if your console doesn't have support for colors
coloredConsole: false

#Auto update for the plugin
auto-update: false
```

**Comment by zubiden** [comment]
> Okay, thank you for the follow up and I will keep an eye on it. Question though, what do I add to `config.yml` to disable the update check?

`check-for-updates: false`
Added with today's update, thanks for feedback
